// -------------------------------------------------------------------------- //
//                             Create variations.                             //
// -------------------------------------------------------------------------- //

// ------------------------ On Hide Amounts Variation ----------------------- //
POST {{flagsUrl}}/projects/{{projectId}}/flags/{{flagKey}}/variations
Content-Type: application/json
Authorization: {{token}}

{
  "key": "on_hide_amounts",
  "name": "On Hide Amounts",
  "description": "Inventory is shown as available/unavailable, in the color green.",
  "variables": {
    "show_amounts": {
      "value": "false"
    },
    "text_color": {
      "value": "green"
    }
  }
}

###

// ------------------------ On Show Amounts Variation ----------------------- //
POST {{flagsUrl}}/projects/{{projectId}}/flags/{{flagKey}}/variations
Content-Type: application/json
Authorization: {{token}}

{
  "key": "on_show_amounts",
  "name": "On Show Amounts",
  "description": "Inventory is shown with amounts, in the color green.",
  "variables": {
    "show_amounts": {
      "value": "true"
    },
    "text_color": {
      "value": "green"
    }
  }
}

###

// ------------------------ On Show Amounts Red Variation ----------------------- 
POST {{flagsUrl}}/projects/{{projectId}}/flags/{{flagKey}}/variations
Content-Type: application/json
Authorization: {{token}}

{
  "key": "on_show_amounts_red",
  "name": "On Show Amounts Red",
  "description": "Inventory is shown with amounts, in the color red.",
  "variables": {
    "show_amounts": {
      "value": "true"
    },
    "text_color": {
      "value": "red"
    }
  }
}
