// -------------------------------------------------------------------------- //
//                              Create audiences.                             //
// -------------------------------------------------------------------------- //

POST {{baseUrl}}/audiences
Content-Type: application/json
Authorization: {{token}}

{
  "conditions": "[\"and\",[\"or\",[\"or\",{\"name\":\"is_logged_in\",\"value\":false,\"match_type\":\"exact\",\"type\":\"custom_attribute\"}]]]",
  "name": "Anonymous Users",
  "project_id": 26592390574
}
###
POST {{baseUrl}}/audiences
Content-Type: application/json
Authorization: {{token}}

{
  "conditions": "[\"and\",[\"or\",[\"or\",{\"name\":\"is_logged_in\",\"value\":true,\"match_type\":\"exact\",\"type\":\"custom_attribute\"}]]]",
  "name": "Authenticated Users",
  "project_id": 26592390574
}
###
POST {{baseUrl}}/audiences
Content-Type: application/json
Authorization: {{token}}

{
  "conditions": "[\"and\",[\"or\",[\"or\",{\"name\":\"days_since_last_order\",\"type\":\"custom_attribute\",\"match_type\":\"le\",\"value\":14}]]]",
  "name": "Recent Purchasers",
  "project_id": 26592390574
}
###
POST {{baseUrl}}/audiences
Content-Type: application/json
Authorization: {{token}}

{
  "conditions": "[\"and\",[\"or\",[\"or\",{\"name\":\"region_state\",\"type\":\"custom_attribute\",\"value\":\"CA\"}]]]",
  "name": "California Visitors",
  "project_id": 26592390574
}
###
POST {{baseUrl}}/audiences
Content-Type: application/json
Authorization: {{token}}

{
  "conditions": "[\"and\",[\"or\",[\"or\",{\"name\":\"is_mobile_user\",\"value\":true,\"match_type\":\"exact\",\"type\":\"custom_attribute\"}]]]",
  "name": "Mobile Web Users",
  "project_id": 26592390574
}
###
POST {{baseUrl}}/audiences
Content-Type: application/json
Authorization: {{token}}

{
  "conditions": "[\"and\",[\"or\",[\"or\",{\"name\":\"is_mobile_app\",\"value\":true,\"match_type\":\"exact\",\"type\":\"custom_attribute\"}]]]",
  "name": "Mobile App Users",
  "project_id": 26592390574
}
###
POST {{baseUrl}}/audiences
Content-Type: application/json
Authorization: {{token}}

{
  "conditions": "[\"and\",[\"or\",[\"or\", {\"value\": true,\"type\": \"custom_attribute\",\"name\": \"is_qa\"}]],[\"or\",[\"or\",{\"name\":\"qa_team\",\"type\":\"custom_attribute\",\"value\":\"1\"}]]]",
  "name": "QA Team 1",
  "project_id": 26592390574
}
###
POST {{baseUrl}}/audiences
Content-Type: application/json
Authorization: {{token}}

{
  "conditions": "[\"and\",[\"or\",[\"or\", {\"value\": true,\"type\": \"custom_attribute\",\"name\": \"is_qa\"}]],[\"or\",[\"or\",{\"name\":\"qa_team\",\"type\":\"custom_attribute\",\"value\":\"2\"}]]]",
  "name": "QA Team 2",
  "project_id": 26592390574
}
